// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    EmojiLabel: typeof import('./src/components/EmojiLabel.vue')['default']
    Home: typeof import('./src/components/home.vue')['default']
    SettingsView: typeof import('./src/components/SettingsView.vue')['default']
  }
}

export { }
